theme: jekyll-theme-cayman
title: >-
  Succinct Data Structure Library
  <style>
    input {
      width: calc(100% - 100px);
    }
    input, button {
      height: 2em;
      padding: 4px;
    }
    td, input {
      font-family: monospace;
    }
    td {
      text-align: right;
    }
    td.hover {
      background: #dfe;
    }
  </style>
description: >-
  JavaScript port of <a style='color: inherit' href='https://github.com/simongog/sdsl-lite'>Simon Gog's popular C++ library</a>

