theme: jekyll-theme-cayman
title: Succinct Data Structure Library
description: >-
  JavaScript port of <a style="color: inherit" href="https://github.com/simongog/sdsl-lite">Simon Gog's popular C++ library</a>

